### ISSUE TITLE
Faild to execute build & install according to the Golang Tutorial

### ISSUE THREAD

**Issue by JasonYjz** [Tencent/MMKV#939]
Hi,

During the operation in following th Golang Tutorial, faced the below issue.
![image](https://user-images.githubusercontent.com/37281108/185519792-6d9e8abd-9974-435c-98d6-69d1032c2c4f.png)

Could you help for this? Thans in advance.

_Env:
[jasyu@manjaro golang]$ **uname -a**
Linux manjaro 5.15.60-1-MANJARO #1 SMP PREEMPT Thu Aug 11 13:14:05 UTC 2022 x86_64 GNU/Linux
[jasyu@manjaro golang]$ **cmake --version**
cmake version 3.23.3_

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by lingol** [comment]
Which compiler do you use and what's the version of it?

**Comment by JasonYjz** [comment]
[jasyu@manjaro golang]$ **gcc --version**
gcc (GCC) 12.1.1 20220730
Copyright © 2022 Free Software Foundation, Inc.

MMKV: v1.2.14

May I need to upgrade the gcc version?

**Comment by lingol** [comment]
No, you don't need to do that. I'll check & fix it later.

**Comment by lingol** [comment]
It's fixed in the dev branch.

**Comment by JasonYjz** [comment]
Yes, thanks for your support in time firstly. The compile step is OK now, but error occurs in the test MMKV. BTW, the go.mod is already modified to actual directory.
![image](https://user-images.githubusercontent.com/37281108/185568265-2ef545d8-0592-44ba-bbcb-301cdb25b312.png)

Pls see my below record.

```
[jasyu@manjaro test]$ pwd
/home/jasyu/work/MMKV/POSIX/golang/test

[jasyu@manjaro test]$ ls -al ../tencent.com/mmkv/
总计 60
drwxr-xr-x 3 jasyu jasyu  4096  8月19日 14:54 .
drwxr-xr-x 3 jasyu jasyu  4096  8月19日 14:54 ..
-rw-r--r-- 1 jasyu jasyu  3083  8月19日 14:53 callback.go
-rw-r--r-- 1 jasyu jasyu 16040  8月19日 14:54 golang-bridge.cpp
-rw-r--r-- 1 jasyu jasyu  3788  8月19日 14:53 golang-bridge.h
-rw-r--r-- 1 jasyu jasyu    33  8月19日 14:53 go.mod
drwxr-xr-x 2 jasyu jasyu  4096  8月19日 14:54 lib
-rw-r--r-- 1 jasyu jasyu 16316  8月19日 14:53 mmkv.go
-rw-r--r-- 1 jasyu jasyu   899  8月19日 14:53 mmkv_test.go

[jasyu@manjaro test]$ ls -al ../tencent.com/mmkv/lib/
总计 2044
drwxr-xr-x 2 jasyu jasyu    4096  8月19日 14:54 .
drwxr-xr-x 3 jasyu jasyu    4096  8月19日 14:54 ..
-rw-r--r-- 1 jasyu jasyu 1991370  8月19日 14:54 libcore.a
-rw-r--r-- 1 jasyu jasyu   89450  8月19日 14:54 libmmkv.a

[jasyu@manjaro test]$ cat go.mod
module mmkv_test

go 1.15

replace tencent.com/mmkv => ../tencent.com/mmkv

require tencent.com/mmkv v0.0.0-00010101000000-000000000000
```

How can I fix this issue?

**Comment by lingol** [comment]
Google about "**golang ld skipping incompatible**" and solve it yourself. 
It's your golang environmental problem, not MMKV's problem.

**Comment by lingol** [comment]
Additional information for you: Google about "**linux check architecture of binary**".

**Comment by JasonYjz** [comment]
So far, still cannot find a effected solution, seems that it is a little complicated. Anyway, still thanks for your information a lot.

**Comment by JasonYjz** [comment]
One thing is very confused for me. First, this compiled libraray for x86-64, and the build os envrionment is also x86_64. According to my understanding, should meet the requirement.

**Comment by lingol** [comment]
And you still don't bother to look into your golang environment. (Does your go environment requires 32 or 64bit?)

**Comment by JasonYjz** [comment]
After reinstall golang package, it is ok now.  haha, you did give a big clue for me, thanks very much.
